# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPoc < Formula
  desc ""
  homepage "https://github.com/wahyudibo/goreleaser-poc"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.0/goreleaser-poc_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ebf98ef52a34dcafee8e4b6da46dd78a8b254d54487f4125ba2fd7cb696c82d0"

      def install
        bin.install "goreleaser-poc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.0/goreleaser-poc_0.1.0_Darwin_arm64.tar.gz"
      sha256 "206caa4272b770ae321428545d8f07d205343b1f820706191eb8e0f502c7e6dd"

      def install
        bin.install "goreleaser-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.0/goreleaser-poc_0.1.0_Linux_x86_64.tar.gz"
      sha256 "809357fd15231f2ecd6227d5334a17b190d662c5f19567c16a1f687fe56fb4ad"

      def install
        bin.install "goreleaser-poc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.0/goreleaser-poc_0.1.0_Linux_arm64.tar.gz"
      sha256 "dcc67927239cfe3e2db26b853982ad965dbf9b79192db954321a920a2f7336c5"

      def install
        bin.install "goreleaser-poc"
      end
    end
  end
end
