# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPoc < Formula
  desc ""
  homepage "https://github.com/wahyudibo/goreleaser-poc"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_darwin_arm64.tar.gz"
      sha256 "ef95a66a601dd302846ef7faef1ff13243f955fc33f036ac0fb9d32f7d85379b"

      def install
        bin.install "goreleaser-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_darwin_x86_64.tar.gz"
      sha256 "a17eb15124d9a7e6d4be46070616c77883a869ce43214cb9b9685f6a8ca4a667"

      def install
        bin.install "goreleaser-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_linux_x86_64.tar.gz"
      sha256 "e59ed24553f01c7d210f47ee2c9276edba687f7d36a85e1b84ec2d9079817ac1"

      def install
        bin.install "goreleaser-poc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_linux_arm64.tar.gz"
      sha256 "869a3eb5417beb96049cb86bef81eb558f53f8a9f1633df2e7f90a74987aacf7"

      def install
        bin.install "goreleaser-poc"
      end
    end
  end
end
