# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserPoc < Formula
  desc ""
  homepage "https://github.com/wahyudibo/goreleaser-poc"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_darwin_arm64.tar.gz"
      sha256 "351a62861878e335702f55937e2ce638af6a476077da66a9d64ff80d7ee12823"

      def install
        bin.install "goreleaser-poc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_darwin_x86_64.tar.gz"
      sha256 "bf9b5438317fe0a2e47c5caf8208c1b4cc737b33ea2a5eec7f1390ce862593f1"

      def install
        bin.install "goreleaser-poc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_linux_x86_64.tar.gz"
      sha256 "70da50c7cd04b05c13bcd1835d4f04d67eb551d692767653be0bbad0fc4386a3"

      def install
        bin.install "goreleaser-poc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wahyudibo/goreleaser-poc/releases/download/v0.1.2/goreleaser-poc_v0.1.2_linux_arm64.tar.gz"
      sha256 "3ee431983239e9747eac1c964742973ace8e37d9f5f8a0549561570745cd0ed7"

      def install
        bin.install "goreleaser-poc"
      end
    end
  end
end
